CC=javac
TARGET=mainacv01


all: clean $(TARGET).class


$(TARGET).class: $(TARGET).java
	$(CC) $<
# 	$(CC) $<


clean:
	-rm *.class
# 	-rm $(TARGET).aux
# 	-rm $(TARGET).log
# 	-rm $(TARGET).pdf
# 	-rm $(TARGET).toc
# 	-rm $(TARGET).out
